image: gitlab-registry.cern.ch/industrial-controls/sw-infra/jenkins/mvn-plus-jdk

stages:
  - build
  - deploy 
  - release
  - sonar

# Get the settings file from c2mon project
before_script:
  - curl -O -L https://cern.ch/maven/settings-ci.xml

# Fully build and publish master branch
build_and_publish:
  stage: deploy
  script: 
    - mvn -U -B deploy -Djavax.net.ssl.trustStore=${JAVA_HOME}/jre/lib/security/cacerts --settings settings-ci.xml
  only:
    - master
  except:
    - tags
    
# Just run tests on feature branches
build:
  stage: build
  script:
    - mvn -U -B test -Djavax.net.ssl.trustStore=${JAVA_HOME}/jre/lib/security/cacerts --settings settings-ci.xml
  except:
    - master
    
sonar_preview:
  stage: sonar
  script:
    - mvn -q -U -B clean compile sonar:sonar -Dmaven.test.skip=true -Dsonar.host.url=${SONAR_URL} -Djavax.net.ssl.trustStore=${JAVA_HOME}/jre/lib/security/cacerts -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.max_major_issues_gate=0 --settings settings-ci.xml
  except:
    - master
    - tags

quality_assurance:
  stage: sonar
  script:
    - mvn package sonar:sonar -Dmaven.test.skip=true -Dsonar.host.url=${SONAR_URL} -Djavax.net.ssl.trustStore=${JAVA_HOME}/jre/lib/security/cacerts -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml --settings settings-ci.xml
  only:
    - master

