version: "3.8"
services:

  c2mon:
    image: cern/c2mon:1.9.3-SNAPSHOT
    ports:
      - "9001:9001"
    environment:
      - C2MON_SERVER_ELASTICSEARCH_ENABLED=false
      - C2MON_SERVER_JMS_EMBEDDED=false
      - C2MON_SERVER_JMS_URL=tcp://mq:61616
      - C2MON_SERVER_CACHEDBACCESS_JDBC_VALIDATION-QUERY=SELECT 1
      - C2MON_SERVER_JDBC_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
      - C2MON_SERVER_JDBC_URL=jdbc:mysql://db/tim
      - C2MON_SERVER_JDBC_USERNAME=root
      - C2MON_SERVER_CACHEDBACCESS_JDBC_JDBC-URL=jdbc:mysql://db/tim
      - C2MON_SERVER_HISTORY_JDBC_JDBC-URL=jdbc:mysql://db/tim
      - C2MON_SERVER_CONFIGURATION_JDBC_JDBC-URL=jdbc:mysql://db/tim
      - C2MON_SERVER_TESTMODE=false
    restart: on-failure
    
  mq:
    image: cern/c2mon-ext:activemq-5.15.6-c2mon-1.9.0
    ports:
      - "61616:61616"
      - "61614:61614"

  db:
    image: cern/c2mon-ext:mysql-5.7.15-c2mon-1.9.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"

  grafana:
    image: cern/c2mon-ext:grafana-6.1.2-c2mon-1.9.0
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor

  c2mon-web:
    image: cern/c2mon-web-ui:0.1.14-SNAPSHOT
    ports:
      - "3306"
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - C2MON_CLIENT_JMS_URL=tcp://mq:61616 
      - C2MON_CLIENT_HISTORY_JDBC_URL=jdbc:mysql://db/tim
      - C2MON_CLIENT_HISTORY_JDBC_USERNAME=root
      - C2MON_CLIENT_HISTORY_JDBC_VALIDATION-QUERY=SELECT 1